name: Print Python Files

on:
  schedule:
    - cron: '17 13 * * *'  # Run every day at 13:17 Algeria time

jobs:
  print_python_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Python files
        run: |
          echo "Python files found:"
          find . -type f -name "*.py" -exec echo {} \;
