name: Bandit Scan

on:
  workflow_dispatch:

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check if triggered by nesrinetestcs
        if: github.actor == 'nesrinetestcs'
        run: echo "Workflow triggered by nesrinetestcs"

      - name: Checkout code
        if: github.actor == 'nesrinetestcs'
        uses: actions/checkout@v2

      - name: Set up Python
        if: github.actor == 'nesrinetestcs'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust as needed

      - name: Install Bandit
        if: github.actor == 'nesrinetestcs'
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit on Python files
        if: github.actor == 'nesrinetestcs'
        run: |
          echo "Running Bandit on Python files:"
          echo "[" > bandit_results.json  # Start JSON array
          find . -type f -name "*.py" -exec bandit -f json {} \; >> bandit_results.json  # Append results of each file
          echo "]" >> bandit_results.json  # End JSON array

      - name: Upload Bandit results as artifact
        if: github.actor == 'nesrinetestcs'
        uses: actions/upload-artifact@v2
        with:
          name: bandit-results
          path: bandit_results.json

      - name: Run verify.py script
        if: github.actor == 'nesrinetestcs'
        run: python verify.py
