name: YARA Scan
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yara-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install YARA
      run: sudo apt-get install yara

    - name: Run YARA scan
      run: yara -r contains_yes_rule.yar ./

    - name: Display result
      run: echo "yey"
      if: success()
